/* Contrary to config.c, this code is *not* autogenerated.
 */

#ifndef TEST
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif//TEST

extern unsigned int auto_config_descriptor_length;
extern const char auto_config_descriptor[];
