/* Contrary to config.c, this code is *not* autogenerated.
 */

#include <avr/io.h>
#include <avr/pgmspace.h>

extern unsigned int auto_config_descriptor_length;
extern const char auto_config_descriptor[];
