/* Contrary to config.c, this code is *not* autogenerated.
 */

#ifndef __TEST__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif//__TEST__

extern unsigned int auto_config_descriptor_length;
extern const char auto_config_descriptor[];
