/* Contrary to config.c, this code is *not* autogenerated.
 */

#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#define PROGMEM
#endif//__AVR__

extern unsigned int auto_config_descriptor_length;
extern const char auto_config_descriptor[];
